networks:
  monitoring:
    driver: bridge

services:
  DB:
    image: postgres:12.4-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '14022004'
      POSTGRES_DB: core
    ports:
      - '5432:5432'
    networks:
      - monitoring
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  DB-ADMINER:
    image: dockette/adminer:full
    container_name: adminer_db
    restart: always
    ports:
      - '5051:80'
    networks:
      - monitoring

  MINIO:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: '14022004'
      MINIO_UPDATE: "off"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    networks:
      - monitoring

  BACKEND:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - DB
      - MINIO
    networks:
      - monitoring