name: LINT & TEST

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint-test-build:
    name: Run ESLint, Prettier, Tests and build
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci